name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  PRIVATE_DOCKER_REGISTRY: ${{ secrets.REGISTRY_HOSTNAME }}
  PRIVATE_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  PRIVATE_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Build Web
      run: bin/build-web.sh
      
    - name: Build Container
      run: bin/build-container.sh
      
    - name: List Docker
      run: "docker images | sort"

    - name: Push Container
      run: bin/push-container.sh
