name: Build

on:
  workflow_dispatch: {}
  push:
    branches-ignore: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches-ignore: [ master ]
    paths-ignore:
      - '**.md'

env:
  PRIVATE_DOCKER_REGISTRY: ${{ secrets.REGISTRY_HOSTNAME }}
  PRIVATE_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  PRIVATE_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.100-rc.1.22431.12'
  
    - name: Build Web
      run: bin/build-web.sh
      
    - name: Build Container
      run: bin/build-container.sh
