name: Build and Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  PRIVATE_DOCKER_REGISTRY: ${{ secrets.REGISTRY_HOSTNAME }}
  PRIVATE_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  PRIVATE_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
  
    - name: Build Web
      run: bin/build-web.sh
      
    - name: Build Container
      run: bin/build-container.sh
      
    - name: List Docker
      run: "docker images | sort"

    - name: Push Container
      run: bin/push-container.sh
